apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: shortlink-app
  description: Shortlink app buat belajar Devops
  # Example for optional annotations
  annotations:
    github.com/project-slug: penicili/myshortlink
  #   backstage.io/techdocs-ref: dir:.
spec:
  type: service
  owner: development
  lifecycle: experimental
