apiVersion: apps/v1
kind: Deployment
metadata:
  name: shortlink-app
  labels:
    app: shortlink
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shortlink
  template:
    metadata:
      labels:
        app: shortlink
    spec:
      containers:
      - name: shortlink
        image: penicili/myshortlink:27-08
        ports:
        - containerPort: 8000
        env:
        - name: DB_HOST
          value: postgres-service:5432
        - name: DB_USER
          value: postgres
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: postgres-password
---
kind: Service
apiVersion: v1
metadata:
  name:  shortlink-app
spec:
  selector:
    app:  shortlink
  type:  NodePort
  ports:
  - name:  fastapi
    port:  8000
    targetPort:  8000