apiVersion: apps/v1
kind: Deployment
metadata:
  name: shortlink-app
  labels:
    app: shortlink
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shortlink
  template:
    metadata:
      labels:
        app: shortlink
    spec:
      containers:
      - name: shortlink
        image: penicili/myshortlink:latest
        ports:
        - containerPort: 8080
---
kind: Service
apiVersion: v1
metadata:
  name:  Service Name
spec:
  selector:
    app:  Selector Label
  type:  LoadBalancer | ClusterIP | NodePort
  ports:
  - name:  name-of-the-port
    port:  80
    targetPort:  8080